/** Generated from references/capabilities.yaml. Do not edit this file. */
export type CapabilityKind = "package" | "mcp" | "extension";

export type CapabilityDefinition = {
  readonly id: string;
  readonly kind: CapabilityKind;
  readonly purpose: string;
  readonly owner: string;
  readonly trigger: string;
  readonly prerequisites: readonly string[];
  readonly readiness: string;
  readonly fallback: string;
  readonly status_signal: {
    readonly source: string;
    readonly states: readonly string[];
    readonly description: string;
    readonly sensitive: false;
  };
  readonly probe: {
    readonly type: CapabilityKind;
    readonly name?: string;
    readonly server?: string;
    readonly launcher?: string | null;
    readonly required_env?: readonly string[];
    readonly auth?: string;
  };
  readonly package?: { readonly name: string; readonly spec: string };
  readonly mcp?: {
    readonly server: string;
    readonly launcher?: string | null;
    readonly required_env: readonly string[];
    readonly auth: string;
  };
  readonly extension?: { readonly name: string; readonly source: string };
  readonly install_state: { readonly action: string; readonly state: string };
  readonly source: Record<string, string>;
};

export const CAPABILITY_CONTRACT_VERSION = 1 as const;
// prettier-ignore
export const CAPABILITIES: readonly CapabilityDefinition[] = [
  {
    "id": "package.pi-mcp-adapter",
    "kind": "package",
    "purpose": "Load Pi MCP configuration and expose managed servers through the adapter proxy.",
    "owner": "Pi MCP adapter",
    "trigger": "Use when a task needs a configured managed MCP server; do not invoke it for unrelated local work.",
    "prerequisites": [
      "Pi CLI",
      "Pi MCP configuration"
    ],
    "readiness": "The package is present in the local Pi package listing.",
    "fallback": "Use native repository tools or report that managed MCP access is unavailable.",
    "status_signal": {
      "source": "local-package-listing",
      "states": [
        "installed",
        "missing",
        "unknown"
      ],
      "description": "Reports only local package presence; it does not report authentication, server health, or session usage.",
      "sensitive": false
    },
    "probe": {
      "type": "package",
      "name": "pi-mcp-adapter"
    },
    "package": {
      "name": "pi-mcp-adapter",
      "spec": "npm:pi-mcp-adapter"
    },
    "install_state": {
      "action": "mcpAdapterAction",
      "state": "mcpAdapterState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "package.pi-observational-memory",
    "kind": "package",
    "purpose": "Provide long-session compaction continuity for Pi conversations.",
    "owner": "Pi observational memory",
    "trigger": "Use when a long session needs compaction continuity; do not add a second memory layer.",
    "prerequisites": [
      "Pi CLI"
    ],
    "readiness": "The package is present in the local Pi package listing.",
    "fallback": "Continue with the active session and report that compaction continuity is unavailable.",
    "status_signal": {
      "source": "local-package-listing",
      "states": [
        "installed",
        "missing",
        "unknown"
      ],
      "description": "Reports only local package presence; it does not persist or expose prompts, memory contents, or usage telemetry.",
      "sensitive": false
    },
    "probe": {
      "type": "package",
      "name": "pi-observational-memory"
    },
    "package": {
      "name": "pi-observational-memory",
      "spec": "npm:pi-observational-memory"
    },
    "install_state": {
      "action": "piObservationalMemoryAction",
      "state": "piObservationalMemoryState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "package.pi-usage",
    "kind": "package",
    "purpose": "Provide Pi usage reporting when the installed extension supports it.",
    "owner": "Pi usage extension",
    "trigger": "Use only when usage reporting is requested or the active Pi session exposes it; it is not a reason to add telemetry calls to unrelated work.",
    "prerequisites": [
      "Pi CLI"
    ],
    "readiness": "The package is present in the local Pi package listing.",
    "fallback": "Do not synthesize usage data; report that usage reporting is unavailable.",
    "status_signal": {
      "source": "local-package-listing",
      "states": [
        "installed",
        "missing",
        "unknown"
      ],
      "description": "Reports only local package presence; this contract does not persist usage telemetry or claim that the package was used in this session.",
      "sensitive": false
    },
    "probe": {
      "type": "package",
      "name": "@sreetej510/pi-usage"
    },
    "package": {
      "name": "@sreetej510/pi-usage",
      "spec": "npm:@sreetej510/pi-usage"
    },
    "install_state": {
      "action": "piUsageAction",
      "state": "piUsageState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "package.pi-anthropic-auth",
    "kind": "package",
    "purpose": "Provide Pi authentication support for Anthropic providers.",
    "owner": "Pi Anthropic auth extension",
    "trigger": "Use when Anthropic provider authentication is missing or explicitly needs attention; do not prompt for auth on unrelated tasks.",
    "prerequisites": [
      "Pi CLI",
      "User-approved provider authentication"
    ],
    "readiness": "The package is present in the local Pi package listing; provider authentication remains unverified.",
    "fallback": "Use an already configured provider or report that Anthropic authentication needs user action.",
    "status_signal": {
      "source": "local-package-listing",
      "states": [
        "installed",
        "missing",
        "unknown"
      ],
      "description": "Reports only local package presence; it never reads, prints, or persists credentials or tokens.",
      "sensitive": false
    },
    "probe": {
      "type": "package",
      "name": "@gotgenes/pi-anthropic-auth"
    },
    "package": {
      "name": "@gotgenes/pi-anthropic-auth",
      "spec": "npm:@gotgenes/pi-anthropic-auth"
    },
    "install_state": {
      "action": "piAnthropicAuthAction",
      "state": "piAnthropicAuthState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "package.pi-intercom",
    "kind": "package",
    "purpose": "Connect same-CWD Pi sessions for explicit planner and worker coordination.",
    "owner": "Pi Intercom",
    "trigger": "Use when the user explicitly selects planner/worker roles or a worker-to-planner handoff is required.",
    "prerequisites": [
      "Pi CLI",
      "Same-CWD session coordination"
    ],
    "readiness": "The package is present in the local Pi package listing; peer connectivity is not probed here.",
    "fallback": "Remain in solo/Off mode or report the coordination gap; never invent a peer or handoff.",
    "status_signal": {
      "source": "local-package-listing",
      "states": [
        "installed",
        "missing",
        "unknown"
      ],
      "description": "Reports only local package presence; it does not enumerate peers, persist messages, or claim delivery.",
      "sensitive": false
    },
    "probe": {
      "type": "package",
      "name": "pi-intercom"
    },
    "package": {
      "name": "pi-intercom",
      "spec": "npm:pi-intercom"
    },
    "install_state": {
      "action": "piIntercomAction",
      "state": "piIntercomState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "package.pi-ask-user-question",
    "kind": "package",
    "purpose": "Provide grouped structured choices for material user-facing decisions and blockers.",
    "owner": "Pi ask-user-question extension",
    "trigger": "Use for a material interactive decision or blocker that needs 2–4 concrete options; do not ask questions for routine confirmations.",
    "prerequisites": [
      "Pi CLI",
      "Interactive UI"
    ],
    "readiness": "The package is present in the local Pi package listing; an interactive UI is still required.",
    "fallback": "Ask one focused plain-text question when the package or interactive UI is unavailable.",
    "status_signal": {
      "source": "local-package-listing",
      "states": [
        "installed",
        "missing",
        "unknown"
      ],
      "description": "Reports only local package presence; it does not persist question content or user responses.",
      "sensitive": false
    },
    "probe": {
      "type": "package",
      "name": "@juicesharp/rpiv-ask-user-question"
    },
    "package": {
      "name": "@juicesharp/rpiv-ask-user-question",
      "spec": "npm:@juicesharp/rpiv-ask-user-question"
    },
    "install_state": {
      "action": "piAskUserQuestionAction",
      "state": "piAskUserQuestionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "package.pi-lsp",
    "kind": "package",
    "purpose": "Route on-demand diagnostics and source actions through configured language servers.",
    "owner": "Pi LSP extension",
    "trigger": "Use on changed source when its file type has a ready configured language server and diagnostics or a source action reduces uncertainty.",
    "prerequisites": [
      "Pi CLI",
      "Relevant language-server command on PATH",
      "Project or user LSP configuration when defaults are insufficient"
    ],
    "readiness": "The package is present in the local Pi package listing, but operational diagnostics require a relevant configured language-server executable; this status surface does not inspect that route.",
    "fallback": "Use repository-local lint, typecheck, and tests and report the missing or unsupported language-server route.",
    "status_signal": {
      "source": "local-package-listing-and-route-availability",
      "states": [
        "installed",
        "missing",
        "unknown"
      ],
      "description": "Reports package presence only; it does not inspect language-server configuration or executables, start servers, inspect source, or persist diagnostics.",
      "sensitive": false
    },
    "probe": {
      "type": "package",
      "name": "@narumitw/pi-lsp"
    },
    "package": {
      "name": "@narumitw/pi-lsp",
      "spec": "npm:@narumitw/pi-lsp"
    },
    "install_state": {
      "action": "piLspAction",
      "state": "piLspState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "package.pi-todo",
    "kind": "package",
    "purpose": "Provide Pi's todo tool, /todos command, and persistent overlay.",
    "owner": "Pi Todo extension",
    "trigger": "Use when a Pi session needs its todo tool, /todos command, or persistent overlay; this package does not add a b-agentic todo workflow policy.",
    "prerequisites": [
      "Pi CLI"
    ],
    "readiness": "The package is present in the local Pi package listing.",
    "fallback": "Continue without Pi todo support or report that the todo tool is unavailable.",
    "status_signal": {
      "source": "local-package-listing",
      "states": [
        "installed",
        "missing",
        "unknown"
      ],
      "description": "Reports only local package presence; it does not inspect todo content, overlay state, or session usage.",
      "sensitive": false
    },
    "probe": {
      "type": "package",
      "name": "@juicesharp/rpiv-todo"
    },
    "package": {
      "name": "@juicesharp/rpiv-todo",
      "spec": "npm:@juicesharp/rpiv-todo"
    },
    "install_state": {
      "action": "piTodoAction",
      "state": "piTodoState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "mcp.serena",
    "kind": "mcp",
    "purpose": "Answer exact symbol, reference, implementation, diagnostic, and semantic-edit questions.",
    "owner": "Serena MCP",
    "trigger": "After native search/read, use for a concrete exact-symbol, reference, implementation, diagnostic, or semantic-edit need; call initial instructions before first use.",
    "prerequisites": [
      "Serena CLI",
      "Lazy MCP entry configured"
    ],
    "readiness": "The local configuration contains a Serena entry and the Serena launcher is available; onboarding and live server health are not probed.",
    "fallback": "Use native Pi read/search/edit tools and state the precision gap; do not initialize or call Serena for routine file work.",
    "status_signal": {
      "source": "local-config-file-presence-and-launcher",
      "states": [
        "unknown",
        "blocked"
      ],
      "description": "Reports only MCP configuration-file presence and launcher metadata; it never reads entry content or claims onboarding, authentication, server health, or session usage.",
      "sensitive": false
    },
    "probe": {
      "type": "mcp",
      "server": "serena",
      "launcher": "serena",
      "required_env": [],
      "auth": "none"
    },
    "mcp": {
      "server": "serena",
      "launcher": "serena",
      "required_env": [],
      "auth": "none"
    },
    "install_state": {
      "action": "mcpAction",
      "state": "mcpState"
    },
    "source": {
      "template": "pi/configs/mcp.user.template.json",
      "policy": "references/mcp_operations.yaml"
    }
  },
  {
    "id": "mcp.codegraph",
    "kind": "mcp",
    "purpose": "Answer repository-wide architecture, dependency/call-flow, impact, route, and affected-test questions.",
    "owner": "CodeGraph MCP",
    "trigger": "Use only when native inspection leaves a concrete repository-wide architecture, dependency/call-flow, impact, route, or affected-test question; initialize an absent index only for that question.",
    "prerequisites": [
      "CodeGraph CLI",
      "Lazy MCP entry configured",
      "Project index only when that concrete question requires it"
    ],
    "readiness": "The local configuration contains a CodeGraph entry and its launcher is available; index state and live server health are not probed.",
    "fallback": "Use native local search/read and report the resulting repository-wide coverage gap.",
    "status_signal": {
      "source": "local-config-file-presence-and-launcher",
      "states": [
        "unknown",
        "blocked"
      ],
      "description": "Reports only MCP configuration-file presence and launcher metadata; it never reads entry content or claims an initialized index, external verification, or session usage.",
      "sensitive": false
    },
    "probe": {
      "type": "mcp",
      "server": "codegraph",
      "launcher": "codegraph",
      "required_env": [],
      "auth": "none"
    },
    "mcp": {
      "server": "codegraph",
      "launcher": "codegraph",
      "required_env": [],
      "auth": "none"
    },
    "install_state": {
      "action": "mcpAction",
      "state": "mcpState"
    },
    "source": {
      "template": "pi/configs/mcp.user.template.json",
      "policy": "references/mcp_operations.yaml"
    }
  },
  {
    "id": "mcp.context7",
    "kind": "mcp",
    "purpose": "Provide versioned official framework, library, and API documentation facts.",
    "owner": "Context7 MCP",
    "trigger": "Use for a versioned external library/framework/API fact when local sources and lockfiles do not settle the question.",
    "prerequisites": [
      "Lazy MCP entry configured",
      "User-supplied Context7 API key"
    ],
    "readiness": "The local configuration contains a Context7 entry and a non-placeholder key is available; the service and authentication are not probed.",
    "fallback": "Use pinned local lockfiles or official bounded sources and state any unresolved version uncertainty.",
    "status_signal": {
      "source": "local-config-file-presence",
      "states": [
        "unknown",
        "blocked"
      ],
      "description": "Reports only MCP configuration-file presence; it never reads entry content or API-key values and never claims authentication, external health, or session usage.",
      "sensitive": false
    },
    "probe": {
      "type": "mcp",
      "server": "context7",
      "launcher": null,
      "required_env": [
        "CONTEXT7_API_KEY"
      ],
      "auth": "api-key"
    },
    "mcp": {
      "server": "context7",
      "launcher": null,
      "required_env": [
        "CONTEXT7_API_KEY"
      ],
      "auth": "api-key"
    },
    "install_state": {
      "action": "mcpAction",
      "state": "mcpState"
    },
    "source": {
      "template": "pi/configs/mcp.user.template.json",
      "policy": "references/mcp_operations.yaml"
    }
  },
  {
    "id": "mcp.linear",
    "kind": "mcp",
    "purpose": "Retrieve one exact Linear issue and directly linked planning context through a read-only surface.",
    "owner": "Linear MCP",
    "trigger": "Use only when the user supplies an exact Linear issue ID or directly requests linked issue context during planning.",
    "prerequisites": [
      "Read-only lazy MCP entry configured",
      "User-approved Linear OAuth session when required"
    ],
    "readiness": "The local configuration contains the read-only Linear entry; OAuth authentication and the external service are not verified.",
    "fallback": "Plan from repository evidence and user-provided issue text, stating that Linear context is unavailable or unverified.",
    "status_signal": {
      "source": "local-config-file-presence",
      "states": [
        "unknown",
        "blocked"
      ],
      "description": "Reports only MCP configuration-file presence; it never reads entry content or OAuth state and never claims external service health or session usage.",
      "sensitive": false
    },
    "probe": {
      "type": "mcp",
      "server": "linear",
      "launcher": null,
      "required_env": [],
      "auth": "oauth"
    },
    "mcp": {
      "server": "linear",
      "launcher": null,
      "required_env": [],
      "auth": "oauth"
    },
    "install_state": {
      "action": "mcpAction",
      "state": "mcpState"
    },
    "source": {
      "template": "pi/configs/mcp.user.template.json",
      "policy": "references/mcp_operations.yaml"
    }
  },
  {
    "id": "mcp.mobbin",
    "kind": "mcp",
    "purpose": "Provide bounded shipped UI precedent for explicit design-reference or competitive UI comparison work.",
    "owner": "Mobbin MCP",
    "trigger": "Use only for an explicit standalone UI/UX precedent study or competitive comparison; do not use for ordinary factual research, implementation, or visual QA.",
    "prerequisites": [
      "Read-only lazy MCP entry configured",
      "User-approved Mobbin OAuth session when required"
    ],
    "readiness": "The local configuration contains the read-only Mobbin entry; OAuth authentication and the external service are not verified.",
    "fallback": "Use local product evidence or supplied references and label any missing precedent evidence.",
    "status_signal": {
      "source": "local-config-file-presence",
      "states": [
        "unknown",
        "blocked"
      ],
      "description": "Reports only MCP configuration-file presence; it never reads entry content or OAuth state and never claims external service health or session usage.",
      "sensitive": false
    },
    "probe": {
      "type": "mcp",
      "server": "mobbin",
      "launcher": null,
      "required_env": [],
      "auth": "oauth"
    },
    "mcp": {
      "server": "mobbin",
      "launcher": null,
      "required_env": [],
      "auth": "oauth"
    },
    "install_state": {
      "action": "mcpAction",
      "state": "mcpState"
    },
    "source": {
      "template": "pi/configs/mcp.user.template.json",
      "policy": "references/mcp_operations.yaml"
    }
  },
  {
    "id": "mcp.brave-search",
    "kind": "mcp",
    "purpose": "Provide independent current web corroboration and specialized current search modalities.",
    "owner": "Brave Search MCP",
    "trigger": "Use when current or independent public-web corroboration is needed after local and primary-source research, or when a specialized search modality is requested.",
    "prerequisites": [
      "Bun bunx",
      "Lazy MCP entry configured",
      "User-supplied Brave Search API key"
    ],
    "readiness": "The local configuration contains a Brave Search entry, bunx is available, and a non-placeholder key is present; the service is not probed.",
    "fallback": "Use approved primary sources or state that independent current corroboration is unavailable.",
    "status_signal": {
      "source": "local-config-file-presence-and-launcher",
      "states": [
        "unknown",
        "blocked"
      ],
      "description": "Reports only MCP configuration-file presence and launcher metadata; it never reads entry content or API-key values and never claims authentication, external health, or session usage.",
      "sensitive": false
    },
    "probe": {
      "type": "mcp",
      "server": "brave-search",
      "launcher": "bunx",
      "required_env": [
        "BRAVE_API_KEY"
      ],
      "auth": "api-key"
    },
    "mcp": {
      "server": "brave-search",
      "launcher": "bunx",
      "required_env": [
        "BRAVE_API_KEY"
      ],
      "auth": "api-key"
    },
    "install_state": {
      "action": "mcpAction",
      "state": "mcpState"
    },
    "source": {
      "template": "pi/configs/mcp.user.template.json",
      "policy": "references/mcp_operations.yaml"
    }
  },
  {
    "id": "mcp.firecrawl",
    "kind": "mcp",
    "purpose": "Provide bounded public extraction, developer research, papers, and GitHub lookup.",
    "owner": "Firecrawl MCP",
    "trigger": "Use for bounded primary public extraction or research when official docs and local evidence are insufficient; do not use it as a browser-evidence substitute.",
    "prerequisites": [
      "Bun bunx",
      "Lazy MCP entry configured",
      "User-supplied Firecrawl API key"
    ],
    "readiness": "The local configuration contains a Firecrawl entry, bunx is available, and a non-placeholder key is present; the service is not probed.",
    "fallback": "Use Context7, Brave, or other approved bounded sources and state the resulting coverage gap.",
    "status_signal": {
      "source": "local-config-file-presence-and-launcher",
      "states": [
        "unknown",
        "blocked"
      ],
      "description": "Reports only MCP configuration-file presence and launcher metadata; it never reads entry content or API-key values and never claims authentication, external health, or session usage.",
      "sensitive": false
    },
    "probe": {
      "type": "mcp",
      "server": "firecrawl",
      "launcher": "bunx",
      "required_env": [
        "FIRECRAWL_API_KEY"
      ],
      "auth": "api-key"
    },
    "mcp": {
      "server": "firecrawl",
      "launcher": "bunx",
      "required_env": [
        "FIRECRAWL_API_KEY"
      ],
      "auth": "api-key"
    },
    "install_state": {
      "action": "mcpAction",
      "state": "mcpState"
    },
    "source": {
      "template": "pi/configs/mcp.user.template.json",
      "policy": "references/mcp_operations.yaml"
    }
  },
  {
    "id": "mcp.playwright",
    "kind": "mcp",
    "purpose": "Collect requested real-browser, live UI, visual, console/network, and e2e evidence.",
    "owner": "Playwright MCP",
    "trigger": "Use only when browser, live UI, screenshot, visual, or e2e evidence is requested or a stated verification gap requires it.",
    "prerequisites": [
      "Bun bunx",
      "Lazy isolated MCP entry configured",
      "Explicit approval for navigation, screenshots, and external or local artifacts as applicable"
    ],
    "readiness": "The local configuration contains an isolated Playwright entry and bunx is available; no browser is started and no live page is probed.",
    "fallback": "Use supplied or CI evidence and report that real-browser evidence remains unverified.",
    "status_signal": {
      "source": "local-config-file-presence-and-launcher",
      "states": [
        "unknown",
        "blocked"
      ],
      "description": "Reports only MCP configuration-file presence and launcher metadata; it never reads entry content or claims a browser session, screenshot, external page state, or session usage.",
      "sensitive": false
    },
    "probe": {
      "type": "mcp",
      "server": "playwright",
      "launcher": "bunx",
      "required_env": [],
      "auth": "none"
    },
    "mcp": {
      "server": "playwright",
      "launcher": "bunx",
      "required_env": [],
      "auth": "none"
    },
    "install_state": {
      "action": "mcpAction",
      "state": "mcpState"
    },
    "source": {
      "template": "pi/configs/mcp.user.template.json",
      "policy": "references/mcp_operations.yaml"
    }
  },
  {
    "id": "extension.b-agentic-permissions",
    "kind": "extension",
    "purpose": "Apply first-party shell and filesystem permission policy to Pi tool calls.",
    "owner": "b-agentic permissions extension",
    "trigger": "Apply on every relevant Pi tool call; explicit deny and approval gates remain authoritative.",
    "prerequisites": [
      "Installed Pi extension entrypoint"
    ],
    "readiness": "The managed entrypoint exists in the local Pi extensions directory.",
    "fallback": "Do not claim b-agentic safety coverage when the entrypoint is absent; keep dangerous work gated by the remaining runtime controls.",
    "status_signal": {
      "source": "local-extension-file",
      "states": [
        "installed",
        "missing"
      ],
      "description": "Reports only the local managed entrypoint; it does not claim that a tool call occurred or that a decision was auto-approved.",
      "sensitive": false
    },
    "probe": {
      "type": "extension",
      "name": "b-agentic-permissions.ts"
    },
    "extension": {
      "name": "b-agentic-permissions.ts",
      "source": "pi/extensions/b-agentic-permissions.ts"
    },
    "install_state": {
      "action": "extensionAction",
      "state": "extensionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "extension.b-agentic-mcp-permissions",
    "kind": "extension",
    "purpose": "Apply managed MCP, custom-tool, and Intercom approval policy.",
    "owner": "b-agentic MCP permissions extension",
    "trigger": "Apply when a managed MCP, custom tool, or Intercom operation is requested.",
    "prerequisites": [
      "Installed Pi extension entrypoint",
      "Canonical MCP operation policy"
    ],
    "readiness": "The managed entrypoint exists in the local Pi extensions directory.",
    "fallback": "Fail closed for unclassified or unsafe MCP/custom operations; do not bypass approval.",
    "status_signal": {
      "source": "local-extension-file",
      "states": [
        "installed",
        "missing"
      ],
      "description": "Reports only the local managed entrypoint and never claims that an MCP operation was executed.",
      "sensitive": false
    },
    "probe": {
      "type": "extension",
      "name": "b-agentic-mcp-permissions.ts"
    },
    "extension": {
      "name": "b-agentic-mcp-permissions.ts",
      "source": "pi/extensions/b-agentic-mcp-permissions.ts"
    },
    "install_state": {
      "action": "extensionAction",
      "state": "extensionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "extension.b-agentic-auto-mode",
    "kind": "extension",
    "purpose": "Provide explicit opt-in automatic approval while retaining explicit denies.",
    "owner": "b-agentic auto-mode extension",
    "trigger": "Use only after the user explicitly enables /b-auto-mode and confirms the warning.",
    "prerequisites": [
      "Installed Pi extension entrypoint",
      "Interactive confirmation for enablement"
    ],
    "readiness": "The managed entrypoint exists; auto-mode itself remains off until explicitly enabled.",
    "fallback": "Use normal approval prompts and explicit deny behavior.",
    "status_signal": {
      "source": "local-extension-file",
      "states": [
        "installed",
        "missing"
      ],
      "description": "Reports only entrypoint presence; it never reports a persisted prompt, approval decision, or enabled state.",
      "sensitive": false
    },
    "probe": {
      "type": "extension",
      "name": "b-agentic-auto-mode.ts"
    },
    "extension": {
      "name": "b-agentic-auto-mode.ts",
      "source": "pi/extensions/b-agentic-auto-mode.ts"
    },
    "install_state": {
      "action": "extensionAction",
      "state": "extensionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "extension.b-agentic-role",
    "kind": "extension",
    "purpose": "Select and persist explicit Off, planner, or worker role preferences.",
    "owner": "b-agentic role extension",
    "trigger": "Use only when the user selects /b-role or a startup role flag; default behavior is Off.",
    "prerequisites": [
      "Installed Pi extension entrypoint",
      "Explicit role selection"
    ],
    "readiness": "The managed entrypoint exists; the current role is reported separately by Pi.",
    "fallback": "Remain in Off/solo mode and do not infer planner or worker ownership.",
    "status_signal": {
      "source": "local-extension-file",
      "states": [
        "installed",
        "missing"
      ],
      "description": "Reports only entrypoint presence; it does not expose session messages or model preferences.",
      "sensitive": false
    },
    "probe": {
      "type": "extension",
      "name": "b-agentic-role.ts"
    },
    "extension": {
      "name": "b-agentic-role.ts",
      "source": "pi/extensions/b-agentic-role.ts"
    },
    "install_state": {
      "action": "extensionAction",
      "state": "extensionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "extension.b-agentic-planner",
    "kind": "extension",
    "purpose": "Inject the planner-only coordination profile while retaining normal shared tools and policy.",
    "owner": "b-agentic planner extension",
    "trigger": "Use when the explicit active role is planner; it does not implement or mutate the worktree.",
    "prerequisites": [
      "Installed Pi extension entrypoint",
      "Planner role selected"
    ],
    "readiness": "The managed entrypoint exists in the local Pi extensions directory.",
    "fallback": "Use the active role's normal prompt and do not claim planner coordination behavior.",
    "status_signal": {
      "source": "local-extension-file",
      "states": [
        "installed",
        "missing"
      ],
      "description": "Reports only the local managed entrypoint; it does not persist or expose prompts.",
      "sensitive": false
    },
    "probe": {
      "type": "extension",
      "name": "b-agentic-planner.ts"
    },
    "extension": {
      "name": "b-agentic-planner.ts",
      "source": "pi/extensions/b-agentic-planner.ts"
    },
    "install_state": {
      "action": "extensionAction",
      "state": "extensionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "extension.b-agentic-planner-notify",
    "kind": "extension",
    "purpose": "Emit privacy-safe desktop attention signals for planner task completion and user input.",
    "owner": "b-agentic planner notification extension",
    "trigger": "Use only for explicit planner task-complete or user-input attention events.",
    "prerequisites": [
      "Installed Pi extension entrypoint",
      "Planner role and supported desktop notifier"
    ],
    "readiness": "The managed entrypoint exists; notification delivery is not probed.",
    "fallback": "Keep the event in the active session flow and report that desktop notification delivery is unavailable.",
    "status_signal": {
      "source": "local-extension-file",
      "states": [
        "installed",
        "missing"
      ],
      "description": "Reports only entrypoint presence; it does not expose notification payloads or claim delivery.",
      "sensitive": false
    },
    "probe": {
      "type": "extension",
      "name": "b-agentic-planner-notify.ts"
    },
    "extension": {
      "name": "b-agentic-planner-notify.ts",
      "source": "pi/extensions/b-agentic-planner-notify.ts"
    },
    "install_state": {
      "action": "extensionAction",
      "state": "extensionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "extension.b-agentic-worker",
    "kind": "extension",
    "purpose": "Inject the worker implementation profile and sole-writer coordination guidance.",
    "owner": "b-agentic worker extension",
    "trigger": "Use when the explicit active role is worker and a planner handoff assigns work.",
    "prerequisites": [
      "Installed Pi extension entrypoint",
      "Worker role selected"
    ],
    "readiness": "The managed entrypoint exists in the local Pi extensions directory.",
    "fallback": "Remain in the normal solo workflow and do not claim a worker handoff.",
    "status_signal": {
      "source": "local-extension-file",
      "states": [
        "installed",
        "missing"
      ],
      "description": "Reports only the local managed entrypoint; it does not expose handoff content or worktree claims.",
      "sensitive": false
    },
    "probe": {
      "type": "extension",
      "name": "b-agentic-worker.ts"
    },
    "extension": {
      "name": "b-agentic-worker.ts",
      "source": "pi/extensions/b-agentic-worker.ts"
    },
    "install_state": {
      "action": "extensionAction",
      "state": "extensionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "extension.b-agentic-consult",
    "kind": "extension",
    "purpose": "Offer bounded isolated read-only consultation for hard planner decisions and plan reviews.",
    "owner": "b-agentic consult extension",
    "trigger": "Use only when a planner has a hard decision or plan review that benefits from independent bounded advice.",
    "prerequisites": [
      "Installed Pi extension entrypoint",
      "Planner role",
      "Configured consultant model when selected"
    ],
    "readiness": "The managed entrypoint exists; model availability and consultation delivery are not probed.",
    "fallback": "Reason from local evidence and state that independent consultation was not available.",
    "status_signal": {
      "source": "local-extension-file",
      "states": [
        "installed",
        "missing"
      ],
      "description": "Reports only entrypoint presence; it does not persist or expose consultation prompts or responses.",
      "sensitive": false
    },
    "probe": {
      "type": "extension",
      "name": "b-agentic-consult.ts"
    },
    "extension": {
      "name": "b-agentic-consult.ts",
      "source": "pi/extensions/b-agentic-consult.ts"
    },
    "install_state": {
      "action": "extensionAction",
      "state": "extensionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "extension.b-agentic-sync",
    "kind": "extension",
    "purpose": "Refresh managed b-agentic assets or installed runtime tooling from an active Pi session.",
    "owner": "b-agentic sync extension",
    "trigger": "Use only when the user explicitly invokes /b-sync or /b-update and accepts the applicable refresh boundary.",
    "prerequisites": [
      "Installed Pi extension entrypoint",
      "Interactive Pi session for refresh"
    ],
    "readiness": "The managed entrypoint exists; no refresh is started by a status snapshot.",
    "fallback": "Report that in-session refresh is unavailable and leave files unchanged.",
    "status_signal": {
      "source": "local-extension-file",
      "states": [
        "installed",
        "missing"
      ],
      "description": "Reports only entrypoint presence; it does not claim that an update ran or expose command output.",
      "sensitive": false
    },
    "probe": {
      "type": "extension",
      "name": "b-agentic-sync.ts"
    },
    "extension": {
      "name": "b-agentic-sync.ts",
      "source": "pi/extensions/b-agentic-sync.ts"
    },
    "install_state": {
      "action": "extensionAction",
      "state": "extensionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "extension.b-agentic-rule-guard",
    "kind": "extension",
    "purpose": "Guard canonical workflow rules that are not represented by a runtime permission decision.",
    "owner": "b-agentic rule-guard extension",
    "trigger": "Apply when a session attempts to bypass a canonical workflow or coordination rule.",
    "prerequisites": [
      "Installed Pi extension entrypoint"
    ],
    "readiness": "The managed entrypoint exists in the local Pi extensions directory.",
    "fallback": "Do not weaken the kernel or claim rule-guard enforcement when the entrypoint is absent.",
    "status_signal": {
      "source": "local-extension-file",
      "states": [
        "installed",
        "missing"
      ],
      "description": "Reports only the local managed entrypoint; it does not expose prompts or claim a blocked action occurred.",
      "sensitive": false
    },
    "probe": {
      "type": "extension",
      "name": "b-agentic-rule-guard.ts"
    },
    "extension": {
      "name": "b-agentic-rule-guard.ts",
      "source": "pi/extensions/b-agentic-rule-guard.ts"
    },
    "install_state": {
      "action": "extensionAction",
      "state": "extensionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "extension.b-agentic-status",
    "kind": "extension",
    "purpose": "Show a read-only local capability snapshot without starting managed services or persisting session content.",
    "owner": "b-agentic status extension",
    "trigger": "Use only when the user invokes /b-status or asks for local capability readiness.",
    "prerequisites": [
      "Installed Pi extension entrypoint"
    ],
    "readiness": "The managed entrypoint exists and can render the local snapshot.",
    "fallback": "Use the installer report and local files; do not infer live service or usage readiness.",
    "status_signal": {
      "source": "local-extension-file",
      "states": [
        "installed",
        "missing"
      ],
      "description": "Reports only entrypoint presence; the snapshot itself remains in memory and never persists prompts, code, URLs, secrets, or usage telemetry.",
      "sensitive": false
    },
    "probe": {
      "type": "extension",
      "name": "b-agentic-status.ts"
    },
    "extension": {
      "name": "b-agentic-status.ts",
      "source": "pi/extensions/b-agentic-status.ts"
    },
    "install_state": {
      "action": "extensionAction",
      "state": "extensionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  },
  {
    "id": "extension.b-agentic-preview-markdown",
    "kind": "extension",
    "purpose": "Render requested Markdown inline in the Pi TUI and provide source-copy commands.",
    "owner": "b-agentic Markdown preview extension",
    "trigger": "Use when an inline Markdown preview is requested or is the appropriate response presentation surface.",
    "prerequisites": [
      "Installed Pi extension entrypoint",
      "Pi TUI for inline rendering"
    ],
    "readiness": "The managed entrypoint exists; a TUI is required for inline rendering and no preview is opened by a status snapshot.",
    "fallback": "Return concise Markdown text or state that inline preview is unavailable outside the Pi TUI.",
    "status_signal": {
      "source": "local-extension-file",
      "states": [
        "installed",
        "missing"
      ],
      "description": "Reports only the local managed entrypoint; it does not persist preview content or claim that a preview was rendered.",
      "sensitive": false
    },
    "probe": {
      "type": "extension",
      "name": "b-agentic-preview-markdown.ts"
    },
    "extension": {
      "name": "b-agentic-preview-markdown.ts",
      "source": "pi/packages/preview-markdown/extensions/b-agentic-preview-markdown.ts"
    },
    "install_state": {
      "action": "extensionAction",
      "state": "extensionState"
    },
    "source": {
      "installer": "pi/scripts/install.sh"
    }
  }
] as const;
export const CAPABILITY_IDS = new Set(
  CAPABILITIES.map((capability) => capability.id),
);
